AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'lib/tasks/cucumber.rake'

Lint/AmbiguousOperator:
  Enabled: false

Lint/Eval:
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Enabled: true
  Max: 120

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/SignalException:
  Enabled: false
