default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/tracker_development
  username: postgres
  password: postgres

test: &test
  <<: *default
  database: db/tracker_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: db/tracker_production

cucumber:
  <<: *test
