default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/tracker_development

test: &test
  <<: *default
  database: db/tracker_test

production:
  <<: *default
  database: db/tracker_production


cucumber:
  <<: *test
